run:
  timeout: 5m
  skip-dirs:
    - ../../../../usr
    - ../../go
    - cmd/original
    - vendor
    - third_party
    - external
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - "SA1019"
  exclude-rules:
    # Exclude duplicate code and function length and complexity checking in test
    # files (due to common repeats and long functions in test code)
    - path: _(test|gen)\.go
      linters:
        - cyclop
        - dupl
        - gocognit
        - funlen
        - lll

linters-settings:
  errcheck:
    exclude-functions:
      - 'fmt.Errorf'
  govet:
    check-shadowing: true